openapi: 3.0.0
info:
  description: Rest API used by AvalonRestAgent.bundle
  version: "1.0.0"
  title: Avalon Rest API
  contact:
    name: GitHub
    url: https://github.com/joshuaavalon/AvalonRestAgent.bundle
  license:
    name: Apache 2.0
    url: https://github.com/joshuaavalon/AvalonRestAgent.bundle/blob/master/LICENSE
tags:
  - name: agent
    description: API calls used by AvalonRestAgent.bundle
paths:
  /show:
    post:
      tags:
        - agent
      summary: Reqeust metadata of a show
      operationId: get_show
      description: |-
        Post the file name of the file and return the best match metadata of a show.
      responses:
        "200":
          description: Matched metadata found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Show"
        "400":
          description: Unable to found matching metadata.
        "422":
          description: Missing or invalid request parameters.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - file
                - path
                - dir
              properties:
                file:
                  type: string
                  example: show - s01e01.mp4
                path:
                  type: string
                  example: /data/show/Season 01/show - s01e01.mp4
                dir:
                  type: string
                  example: /data/show
  /episode:
    post:
      tags:
        - agent
      summary: Reqeust metadata of a episode
      operationId: get_episode
      description: |-
        Post the file name of the file and return the best match metadata of a episode.
      responses:
        "200":
          description: Matched metadata found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Episode"
        "400":
          description: Unable to found matching metadata.
        "422":
          description: Missing or invalid request parameters.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - file
                - path
                - dir
                - season
                - episode
              properties:
                file:
                  type: string
                  example: show - s01e01.mp4
                path:
                  type: string
                  example: /data/show/Season 01/show - s01e01.mp4
                dir:
                  type: string
                  example: /data/show/Season 01
                season:
                  type: integer
                  example: 1
                episode:
                  type: integer
                  example: 1
  /movie:
    post:
      tags:
        - agent
      summary: Reqeust metadata of a movie
      operationId: get_movie
      description: |-
        Post the file name of the file and return the best match metadata of a movie.
      responses:
        "200":
          description: Matched metadata found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
        "400":
          description: Unable to found matching metadata.
        "422":
          description: Missing or invalid request parameters.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - file
                - path
                - dir
              properties:
                file:
                  type: string
                  example: movie (2018).mp4
                path:
                  type: string
                  example: /data/movie (2018)/movie (2018).mp4
                dir:
                  type: string
                  example: /data/movie (2018)
  /artist:
    post:
      tags:
        - agent
      summary: Reqeust metadata of an artist
      operationId: get_artist
      description: |-
        Post the file name of the file and return the best match metadata of an artist.
      responses:
        "200":
          description: Matched metadata found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artist"
        "400":
          description: Unable to found matching metadata.
        "422":
          description: Missing or invalid request parameters.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - file
                - path
                - dir
              properties:
                file:
                  type: string
                  example: 01. title.mp3
                path:
                  type: string
                  example: /data/artist/album/01. title.mp3
                dir:
                  type: string
                  example: /data/artist
  /album:
    post:
      tags:
        - agent
      summary: Reqeust metadata of an album
      operationId: get_album
      description: |-
        Post the file name of the file and return the best match metadata of an album.
      responses:
        "200":
          description: Matched metadata found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Album"
        "400":
          description: Unable to found matching metadata.
        "422":
          description: Missing or invalid request parameters.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - file
                - path
                - dir
              properties:
                file:
                  type: string
                  example: 01. title.mp3
                path:
                  type: string
                  example: /data/artist/album/01. title.mp3
                dir:
                  type: string
                  example: /data/artist/album
components:
  schemas:
    Show:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Title
          description: Title of the show
        sort_title:
          type: string
          example: Sort Title
          description: Title used to sort the show
        original_title:
          type: string
          example: オリジナルタイトル
          description: Title of the show in original language
        aired:
          type: string
          format: date
          example: "2018-01-01"
          description: First episode aired date of the show
        content_rating:
          type: string
          example: TV-14
          description: Content rating of the show
        rating:
          type: number
          format: float
          example: 5.5
          description: Rating of the show
        summary:
          type: string
          example: This is the summary of the show.
          description: Summary of the show
        tagline:
          type: array
          items:
            type: string
            example: This is a tagline.
          description: Tagline(s) of the show
        studio:
          type: array
          items:
            type: string
            example: ABC Studio
          description: Studio(s) that produces the show
        genres:
          type: array
          items:
            type: string
            example: Action
          description: Genre(s) of the show
        collections:
          type: array
          items:
            type: string
            example: Action Collection
          description: Collection(s) of the show
        actors:
          type: array
          items:
            $ref: "#/components/schemas/Actor"
        season_summary:
          type: object
          additionalProperties:
            type: string
          example:
            "0": "This is the summary of specials."
            "1": "This is the summary of season 1."
            "2": "This is the summary of season 2."
            "3": "This is the summary of season 3."
        posters:
          type: array
          items:
            type: string
            example: https://example.com/example.png
          description: Show Poster
    Episode:
      type: object
      properties:
        title:
          type: string
          example: Title
          description: Title of the episode
        aired:
          type: string
          format: date
          example: "2018-01-01"
          description: Aired date of the episode
        content_rating:
          type: string
          example: TV-14
          description: Content rating of the episode
        rating:
          type: number
          format: float
          example: 5.5
          description: Rating of the episode
        summary:
          type: string
          example: This is the summary of the episode.
          description: Summary of the episode
        directors:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        writers:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        posters:
          type: array
          items:
            type: string
            example: https://example.com/example.png
          description: Episode Poster            
    Movie:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Title
          description: Title of the movie
        sort_title:
          type: string
          example: Sort Title
          description: Title used to sort the movie
        original_title:
          type: string
          example: オリジナルタイトル
          description: Title of the movie in original language
        aired:
          type: string
          format: date
          example: "2018-01-01"
          description: Aired date of the movie
        content_rating:
          type: string
          example: TV-14
          description: Content rating of the movie
        rating:
          type: number
          format: float
          example: 5.5
          description: Rating of the movie
        summary:
          type: string
          example: This is the summary of the movie.
          description: Summary of the movie
        tagline:
          type: array
          items:
            type: string
            example: This is a tagline.
          description: Tagline(s) of the movie
        studio:
          type: array
          items:
            type: string
            example: ABC Studio
          description: Studio(s) that produces the movie
        genres:
          type: array
          items:
            type: string
            example: Action
          description: Genre(s) of the movie
        collections:
          type: array
          items:
            type: string
            example: Action Collection
          description: Collection(s) of the movie
        actors:
          type: array
          items:
            $ref: "#/components/schemas/Actor"
        directors:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        writers:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        posters:
          type: array
          items:
            type: string
            example: https://example.com/example.png
          description: Movie Poster
    Actor:
      type: object
      required:
        - name
        - role
      properties:
        name:
          type: string
          example: Avalon Joshua
          description: Name of the actor
        role:
          type: string
          example: Role
          description: Role name of the actor
        photo:
          type: string
          format: url
          example: https://example.com/example.png
          description: Photo of the actor
    Album:
      type: object
      properties:
        aired:
          type: string
          format: date
          example: "2018-01-01"
          description: Aired date of the artist
        summary:
          type: string
          example: This is the summary of the artist.
          description: Summary of the artist
        genres:
          type: array
          items:
            type: string
            example: J-Pop
          description: Genre(s) of the artist
        collections:
          type: array
          items:
            type: string
            example: J-Pop Collection
          description: Collection(s) of the artist
        posters:
          type: array
          items:
            type: string
            example: https://example.com/example.png
          description: Album Poster          
    Artist:
      type: object
      properties:
        summary:
          type: string
          example: This is the summary of the artist.
          description: Summary of the artist
        genres:
          type: array
          items:
            type: string
            example: J-Pop
          description: Genre(s) of the artist
        collections:
          type: array
          items:
            type: string
            example: J-Pop Collection
          description: Collection(s) of the artist
        similar:
          type: array
          items:
            type: string
            example: Avalon Joshua
          description: Similar artist(s)
    Person:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Avalon Joshua
          description: Name of the person
        photo:
          type: string
          format: url
          example: https://example.com/example.png
          description: Photo of the person